language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    rooms:
      secure: raHMwe3cIkMf3lqoXOeVmTXgZ7DBneG8qddfSHXxf8EQPahCWi1gYxXlAA5xzibJlnE/C0cSCQSxhNZd/C2gXKj0abWQXWAvFW5ETdYwOYVB111THLLuTRAcADTY9QJuRC4SY3EEj6yjMgMjaDLDn2kUm1VrEafYn4nKpKxEUEe0/qtqyWi++uaauwnIH+o7YbODT/xDLTNKwi5ZWVcAFuVLWM8GbP/g/IsteV73gifx022IdXZfCcbiGk5zhXtwX2kZaHEGEkSJCxUmpCz3194yKDH0Wo/pyNaCb4yC6mbTqEAjGSaETim/s6q62U35j4G+xj7IQrsqFd9sqjr+dQMyFhPpsCKbb2mDLxnsgsc3kgru0sogdY9XGf1rlg9gYWoc3TVV8lW25R3awQNgljXKFNxJoLBCPzqYkcnbDG4eIPi9HwJAysEaFz43kzy1g3ECdbynZ9+btZGHo9u9fsnhDf68mkTDrhY2EtLJ04tlyhFo6vxbW9FsEze6apjQHmlcPPj66YJkRlp7yVY10kUh4PkjnJhvLTEDHipVO3r650h1B9mXAIqKqHIG/sf3zFBvfhDNvkjNte2w1VH5ahOarcb/ReAD604lBSvnobNEOdcbe7axCEeBY2fjYrmsxYZgKTnkrB/T+2SyugqIvo7AGbFCtcpMQY55cTPfsJM=
    on_success: change
    on_failure: always
