language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    secure: v030w5zKY9QVQuW4Lgv3vnkzM14giQyJlHldhgUglkdk1k0NHJ7y7O6+iVVs7lMBb8e5REP4QvUl6/qa+R/R33vh5RThqPKGmkhbu3hnecZzZdbpR+A+xmtbQVHPbhtPVICjzfelbGO2tMhoDnknEzUm3oH4Q2tJSPsvQ1DznK/Izo/iGXqJhS96vDMcwnHYEInM30IV8rAWX+EbEE6YLVNmC8WZT4LjpeIuGHnS4YVMyt6Z+prXrNiNJqH3uvl0dMILtWjnm/Dcwb17QQfHaBYOtyXiO0BrC3kxLOWBWKeOSUMY1zUbiy1SMANfcPloiWpHgkIZmUFh3jlMpgGANHUB5ChP/MBOPizQqGGlsHlgeZYISDavAsDKoNtTfwv34vc1c37HQi/mdd5elS8RmH5PN/UnJCLDApa+/bwb2UY0ZLxJTiHXfqHZgqJ0KM0VHlPthAjEzsVUMWjX1qZv1Z9zX3czpIIgVs19UGL99RNfptKgEkrkDhsnPXqLK4sSXhqLPECZvLOPiqTeSWqnuwEKJnfdVfrdMfv8ucQePYp9mRcNEvLEV+rrsRA83Tk0qbHnGwSgj7/vAdu1hhz3odENBguQYUho9ZP/0fygBucgmlk807tQinfkwk1wHrsH+R91ySdR63nsmIffQmAiCsmFjm8g3VDJqplzDsCFg0M=
  on_failure: always
