language: node_js
node_js:
- '8'
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    rooms:
      secure: CwxwP0Ad8NII5UEGXEfXqMrp159obuwqH7Fkpt5EIf/3MCwiJIzOTn5rSszl01CwO3G9AUqmqEEH/tcfnxjGpXIS4yk9FlyDBVZpHMomonH6HBkTzKr7ZDfvchRXM8zYXxQuTqDxJLYxRiZZ5JEQLZik7Wmk2jkV5g9sHlGr/Cwa26CAdjJP7F6Tk0FZBVUrkGd+AporsqGT84X/Eph8eddFZhvVuYYJJId9WMOP2mNlCkBR3AML4hN1G/m18oHu+4kak8jpEqGpygQ/eHjqKHs6RDel1I8UtrDA5Ib0lFyb+589++FuzjiIS+D49vd0QGzYmIG7WL/30N5P+0IKHwCSfPAO4hfYv/QgbzOiT7mruRlNUl7LgyNf32z5TfNDHIMUt56jklsWjN8ew1J35cEh2Y+Jbv5x4ipSAg9HIgjhuJDRu0UNXWVa3Nymppubqp2ujDVEOOxVANX1mtY6BuerfPl2QiViohDwIX2Ur1TCVpAF4NZhP48//C9HdnjmUidnjRzAftNvrfXWZz0Kcaq8GMcPlBAkL40rIyY50E4/52swSo/UGY5lekDfDlpHyT71r2kavwh61vLosjLzmHDskokOisUWNwR5YMYSh8WOBIwCVBmmyguL9e+As9nebYJlg+FFFmKZFVDs4ndrjwaTpShLYW3R/NpfLNCVDx0=
    on_failure: always
