language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_script:
- npm install
script:
- npm test
notifications:
  slack:
    secure: K/t079LgyjmWbu7bGWptQDwgtGv3QkwGqbb+QtMAu5PtsKs26OwsbvlfG79a3gjl77vQqcaxH0q4aisdKdc0aD8Vgu3bpEENIytEpbQ1lHCl18Zc4LugJOKE0i2CgZCajtknpwNiuexfnTeYTE3FSHHxBSr26+DkU2sFF9QjvSGk8pYTwZwJXhdCeFntESgPcqqZgOfBo8Xen+5QX/fscynmo9H8wGDsPuYrYE6+Vc28H/uWHiEtE/cP8UoHMrVdOPSnZGlZC17lA2SIZBOpy09vWn5/TPfJO8Wg9pL6T1Rc+nMMYZeTytry6WEKM2toF1COGxZIDq40zh1Uc3e9PU2DVwdZkyGBpRZ5JOdPjsOjg28l85xwtm/u9xBwlqLyEyQk9G0W9BA9/qmlS5+RgLP6FkICmBS2Vgp6ecJE/EWxHKL5Y6l073hEsCT/yWrPDr7ZWg70RPraqCJ8tleNMUy+j9BM9CHcDV2H/mt/t0BayPRex1cQW//GRH5mnGt7693FGUQdSWD0PJ6IpqqP0f7RLUUWTdPKAzt7eH7TNCjW42aZPAdlVXnLC7KTXkrY++297BpFKi02JpAVXH0suBkHq2w6Ijn7IXRP8Gkgp1+nFx7bpOPncKikpbonyR6VlvqLJtS0jyTQaS2u77CPcSix2T0sqMJH48TX+6ak6PQ=
  on_failure: always
